[build]
  base = "packages/nextjs/"
  command = "NEXT_PUBLIC_IGNORE_BUILD_ERROR=true yarn build && yarn next export -o out"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"